# Generated by Django 4.1.7 on 2023-02-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
