# Generated by Django 4.1.7 on 2023-02-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemname',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
